### ISSUE TITLE
Why leave addons.mozilla.org ？

### ISSUE THREAD

**Issue by ivysrono** [kevinjacobs/HTTPS-Finder#18]
What happened？

**Comment by talha131** [comment]
I too would like to know the reason.

**Comment by Mosrite** [comment]
+1

**Comment by Tailszefox** [comment]
It seems this add-on has been abandoned, considering the lack of update and the unanswered issues opened both here and on Google Code. I assume the author just doesn't have time to develop it anymore, which is why it was removed from the Addons website. Either by the author or automatically because it stopped working with the latest version of Firefox.

It's too bad, it's a fairly useful extension.
